#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("BlurSample.Resource", IsApplication=true)]

namespace BlurSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::FiveHundredPixels.Resource.Attribute.blurRadius = global::BlurSample.Resource.Attribute.blurRadius;
			global::FiveHundredPixels.Resource.Attribute.downsampleFactor = global::BlurSample.Resource.Attribute.downsampleFactor;
			global::FiveHundredPixels.Resource.Attribute.overlayColor = global::BlurSample.Resource.Attribute.overlayColor;
			global::FiveHundredPixels.Resource.Color.default_overlay_color = global::BlurSample.Resource.Color.default_overlay_color;
			global::FiveHundredPixels.Resource.Integer.default_blur_radius = global::BlurSample.Resource.Integer.default_blur_radius;
			global::FiveHundredPixels.Resource.Integer.default_downsample_factor = global::BlurSample.Resource.Integer.default_downsample_factor;
			global::FiveHundredPixels.Resource.String.library_name = global::BlurSample.Resource.String.library_name;
			global::FiveHundredPixels.Resource.Styleable.PxBlurringView = global::BlurSample.Resource.Styleable.PxBlurringView;
			global::FiveHundredPixels.Resource.Styleable.PxBlurringView_blurRadius = global::BlurSample.Resource.Styleable.PxBlurringView_blurRadius;
			global::FiveHundredPixels.Resource.Styleable.PxBlurringView_downsampleFactor = global::BlurSample.Resource.Styleable.PxBlurringView_downsampleFactor;
			global::FiveHundredPixels.Resource.Styleable.PxBlurringView_overlayColor = global::BlurSample.Resource.Styleable.PxBlurringView_overlayColor;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int blurRadius = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int downsampleFactor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int overlayColor = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int default_overlay_color = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int p0 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int p1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int p2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int p3 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int p4 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int p5 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int p6 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int p7 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int p8 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int p9 = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int blurred_view = 2131165184;
			
			// aapt resource value: 0x7f07000a
			public const int blurring_view = 2131165194;
			
			// aapt resource value: 0x7f070001
			public const int image0 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int image1 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int image2 = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int image3 = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int image4 = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int image5 = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int image6 = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int image7 = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int image8 = 2131165193;
			
			// aapt resource value: 0x7f07000c
			public const int shift_button = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int shuffle_button = 2131165195;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f040000
			public const int default_blur_radius = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int default_downsample_factor = 2130968577;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060002
			public const int app_name = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int hello = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int library_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PxBlurringView = new int[]
			{
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int PxBlurringView_blurRadius = 0;
			
			// aapt resource value: 1
			public const int PxBlurringView_downsampleFactor = 1;
			
			// aapt resource value: 2
			public const int PxBlurringView_overlayColor = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
